name: metagenomic_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2
  - gzip
  - seqtk
  - bbmap
  - pear
  - emboss
  - pigz
  - megahit
  - bwa
  - samtools
  - picard
  - fastp
  - file
  - r-base
  - r-tidyverse
  - r-optparse
  - bioconductor-shortread
  - r-doparallel
  - bioconductor-dada2
  - tbb=2020.2  # Required for dada2 compatibility
