name: metagenomic_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2
  - gzip
  - seqtk
  - bbmap
  - pear
  - r-base
  - r-tidyverse
  - r-optparse
  - bioconductor-shortread
  - r-doparallel
  - bioconductor-dada2
